name: evolution-mapper-frontend
region: syd1
services:
- name: web
  source_dir: /
  github:
    repo: jarrodharvey/evolution-mapper-frontend
    branch: main
  run_command: serve -s build -l $PORT
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  health_check:
    http_path: /
  envs:
  - key: REACT_APP_BACKEND_URL
    value: https://170.64.241.9
  - key: REACT_APP_API_KEY
    value: evo-spzw1H4RZIQXAqcYNZ60NsJfKAG5BKBz
  build_command: npm ci && npm run build && npm install -g serve